template: |
  ## What’s Changed

  $CHANGES
  
  $CONTRIBUTORS
  
  $PREVIOUS_TAG
  
  $REPOSITORY
  
  
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
